# safelist
branches:
  only:
    - master
language: node_js
node_js:
  - "14"
install:
  - npm install hexo-cli -g
  - npm install
script: hexo clean && hexo generate
deploy:
  # deploy to github pages
  - provider: pages
    skip_cleanup: true
    target_branch: master
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    repo: wangyucode/wangyucode.github.io
    local_dir: public
  - provider: script
    skip_cleanup: true
    script: node deploy/sftp.js $SERVER_PASSWORD
