# Header
menu:
  archives: /archives/

# Jumbotron
jumbotron:
  welcome: 欢迎光临王郁的小站
  slogan: 博学之、审问之、慎思之、明辨之、笃行之

# Sidebar
widgets:
- recent_posts
- category
- tagcloud
- about
- clustrmaps

about:
  wechat: /img/wechat.jpg
  email: wangyu@wycode.cn
  github: https://github.com/wangyucode


clustrmaps: //cdn.clustrmaps.com/map_v2.js?d=gqBX0NCZ-bHPpFMW_0e6Yy-FapJ0v9V1jVB6HKf1Weo&amp;cl=ffffff&amp;w=a&amp;t=tt

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
favicon: /img/logo_48.png
