# Header
menu:
  博客: /
  归档: /archives
rss: /atom.xml


# Sidebar
widgets:
- category
- recent_posts
- tagcloud



# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
favicon: img/favicon.png
yungentie: 32b5a020f7eb416280e9317a050982ac
