# Header
menu:
  archives: /archives/

# Jumbotron
jumbotron:
  image: /img/bg.jpg
  welcome: 欢迎光临王郁的小站
  slogan: 博学之、审问之、慎思之、明辨之、笃行之

# Sidebar
widgets:
- recent_posts
- category
- tagcloud
- clustrmaps



# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
favicon: /img/logo_48.png
