# Header
menu:
  博客: /
  归档: /archives
rss: /atom.xml


# Sidebar
widgets:
- recent_posts
- category
- tagcloud



# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
favicon: /img/logo_48.png
